# Generated by Django 5.1.6 on 2025-03-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_recipe_name_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
    ]
