# Generated by Django 5.1.6 on 2025-03-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20250310_1500'),
    ]

    operations = [
    ]
